### ISSUE TITLE
GC.1: Strawman governance documents

### ISSUE THREAD

**Issue by mmersmann** [TranslatorIIPrototypes/SRIGovernance#1]
Draft procedures for decision-making and document how these procedures themselves will be updated as necessary over time.

**Comment by mellybelly** [comment]
Governance documents needed:

- [ ] Governance Executive Summary
- [ ] Code of Conduct and Conflict Resolution
- [ ] Collaboration Handbook
- [ ] Roles and Responsibilities
- [ ] Standards and Reference Change Management

Draft documents are being deposited in this [folder](https://drive.google.com/drive/folders/15Co_4N6tm7weWdkmt_OhiC12xbJaeG83)

**Comment by cbizon** [comment]
@karafecho, @stanahalt, @cbizon @patrickkwang please review the docs in the folder above by Tuesday

**Comment by mellybelly** [comment]
Especially helpful will be to add to the Standards and Reference Change Management document, which is quite skeletal at present. I wasn't sure what all we wanted to put on a standards governance change cycle, but knew that we'd need a different cycle for different components that we are aiming to standardize. 

Also note that the idea is to have a prototype that the remaining funded components can actually help iterate on after the March meeting. So the goal is not perfection, but rather something complete enough for community iteration and decision making.
