### ISSUE TITLE
Bringing issues to the steering committee

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#10]
From the Roles and Responsibilities document: "Community members who have additional responsibilities to ensure the smooth running of the project, the principal investigators, and the NCATS Program Officers are eligible to become Steering Committee (SC) members. SC members are expected to participate in strategic planning and approve changes to the governance model. In cases where the Translator community (which includes SC members) fails to reach a consensus (see “decision-making process” in the collaboration handbook), the SC is the entity to resolve the issue. The SC will meet at each hackathon or other in-person event, as well as quarterly online to discuss strategy, progress, and review requested changes to the governance as well as Translator strategy, progress, publications. The agendas will be made publicly available in advance and anyone can make suggestions, but the meetings will be closed. Summaries of discussion and decisions will be made publicly available."

Michel Dumontier comments: "i think any Translator member should be able to make a statement for an issue / decision in advance of the meeting, and this will be included in the discussion." and "it's not clear how the "suggestions" will be handled. i'd like statements to be recorded and discussed."

**Comment by mellybelly** [comment]
I would suggest that the SC have both an open and a closed time. We don't want 100 people to attend the entirety of the SC or nothing will get done; on the other hand, we want transparency and communication. Would this be an acceptable solution? @micheldumontier

**Comment by diatomsRcool** [comment]
I suppose suggestions could be made anywhere, but should be logged in GitHub.

**Comment by diatomsRcool** [comment]
@micheldumontier

**Comment by micheldumontier** [comment]
i don't think we need to make it open. posting the issues to be discussed/decided on github in advance of the meeting would be appropriate.

**Comment by diatomsRcool** [comment]
How about posting the issues in a Google doc?

**Comment by micheldumontier** [comment]
the principle is just that we have the ability and the record of issues raised. it's not clear to me whether github or google doc is most appropriate here.

**Comment by diatomsRcool** [comment]
Got it. Language was added to address the openness of the issues raised and the discussion.
