### ISSUE TITLE
Clinical data WG or committee

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#14]
Should the Clinical data group be a Working Group or a Committee?

**Comment by diatomsRcool** [comment]
@karafecho

**Comment by diatomsRcool** [comment]
@mellybelly

**Comment by karafecho** [comment]
The Clinical Data Working Group is described in the [Prototype Roles & Responsibilities doc](https://docs.google.com/document/d/1BuKHIq3WQf8WtnArt-Ti6UbVY4mynjw1NFawUG3tgEY/edit?usp=sharing). Initial charter and related docs can be found in a subfolder within this [Working Groups Google folder](https://drive.google.com/drive/folders/1ADRSpa9fzz5vVY16upTC_z4uBN3eoMVS).

**Comment by diatomsRcool** [comment]
was there ever a final decision about whether or not this was a working group or a committee?

**Comment by karafecho** [comment]
Nope. I believe Melissa felt pretty strongly about forming a committee, as opposed to a working group, but I'm not sure we need something that formal. Why don't I add this topic to the agenda for the next working group meeting.

**Comment by diatomsRcool** [comment]
Let's go ahead and make it a WG for now. We can talk later about graduating it to a Committee. I'm going to take the text about it out of governance and put it in a WG Charter.

**Comment by diatomsRcool** [comment]
https://docs.google.com/document/d/1HYeJC6mdMLfksEDzGPc6c3EUey8xKFM61o3y63A24TQ/edit#
