### ISSUE TITLE
SC Proxy Voting

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#15]
Michel Dumontier suggests that proxy votes should be allowed for the Steering Committee. This also raises the question of what a quorum should be for the committees. What does the group think?

**Comment by cbizon** [comment]
Just to be explicit, proxy vote means that if member X can't attend that they can designate somebody else to vote for them?  I'm fine with that.

I don't have a strong feeling on quorum.  What's normal?  2/3 or something?

**Comment by diatomsRcool** [comment]
Yes, 2/3. We have that language in the governance docs already. I think that's reasonable. I added language to allow proxy voting.
