### ISSUE TITLE
ITRB 

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#20]
How should we include ITRB in the document?

**Comment by cbizon** [comment]
I'm not sure we need to.    Maybe in the section where we define the teams we could say that the production and other environments will be managed by NCATS ITRB?   And that they set the policies for those environments.

**Comment by diatomsRcool** [comment]
Do we need any mention of how we communicate or interact with ITRB?

**Comment by diatomsRcool** [comment]
Resolved during Internal SRI meeting.
