### ISSUE TITLE
How will the UI Team collaborate with the rest of translator?

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#21]

**Comment by tursynay** [comment]
How would the UI team participate in voting?

**Comment by diatomsRcool** [comment]
I would propose that that UI team is welcome to participate in any WG or Committee, is required to participate in TACT, and does not have voting powers in the Committees.

**Comment by sierra-moxon** [comment]
I am not entirely sure that voting is the way to solve this issue, but I can imagine the UI team helping backend teams (when they need help) limit the scope of development/discussion to those critical 
iteratable bits that are required to support the UI? 

(Understandable if this feedback comes in a different form than voting).

**Comment by diatomsRcool** [comment]
Resolved this during Internal SRI meeting.
