### ISSUE TITLE
Translator Mission and Vision

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#22]
In response to feedback that Translator lacks a shared vision, should we include a mission and vision in our guidelines docs?

**Comment by diatomsRcool** [comment]
There is a process for drafting a mission and vision statement that I've used in the past. We could do this with translator as well with as small or as large a group as we think would work.

**Comment by cbizon** [comment]
Maybe this would be a good TACTivity

**Comment by diatomsRcool** [comment]
agree
