### ISSUE TITLE
Licensing, attribution, and citation

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#24]
Do the guidelines need to include something about licensing, attribution, or citation?

**Comment by cbizon** [comment]
I think yes.   I assume that on licensing we would say "no unlicensed data".   I'm not as sure about attribution or citation?  Which attribution or citation are we talking about?

**Comment by diatomsRcool** [comment]
Are you saying that Translator will not use unlicensed data? Do we have any other requirements for data that we use? How do people cite "Translator"? How do people give attribution for the data sets and Translator components that they use in a query?

**Comment by tursynay** [comment]
The Executive Summary has a section on Minimum Criteria for Translator that talks about licensing and attribution. Should it be moved over to the Collaboration doc?

https://docs.google.com/document/d/1Jg5ZTT_5QlTzDEqm2njA_ecnHDLDyDOrZVXcxZTJ1Yg/edit#heading=h.3znysh7

**Comment by diatomsRcool** [comment]
We will go with the statement in the executive summary
