### ISSUE TITLE
Include users and outside developers in the guideline documents

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#25]

**Comment by cbizon** [comment]
I'm not sure we know what to say here yet.   I don't understand the balance between allowing anybody to stand up a KP versus "the translator app" living in prod itrb environment.

**Comment by diatomsRcool** [comment]
Maybe we have to punt this one for the moment - at least until we get more outside developers involved.

**Comment by diatomsRcool** [comment]
Will revisit this during outside developer hackathon planning.
