### ISSUE TITLE
Process to manage competing use cases and priorities

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#26]

**Comment by cbizon** [comment]
I think that we could/should add a paragraph about TACT, b/c that's what this is for.

**Comment by tursynay** [comment]
@cbizon, we added language about TACT in the Roles and Responsibilities doc. Should we add language elsewhere?
https://docs.google.com/document/d/1-aux54fnbVTACHa2yVN7a7nnanCL5Wkri2DfW4uM_RE/edit

**Comment by cbizon** [comment]
Nope, I think that satisfies this issue.
