### ISSUE TITLE
Only using open terminologies

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#3]
A proposed minimum criterion for Translator is only using open terminologies. "Only open terminologies (i.e., terminologies with a license that allows free redistribution) are used. Cross references to non-open terminologies are permissible."

Andrew Su comments "This would cut out semmeddb (UMLS). Longer term I think the goal is that Larry's team at Colorado would create something that is (much) better based only on open terminologies, but short term I think that might create problems for teams (e.g., +webyrd@gmail.com) that depend on semmed?"

William Byrd comments "Thanks +asu@scripps.edu ! It is both true that we are currently using UMLS, and that we want to get rid of the dependency. In particular, we want to have access to high-quality, comprehensive data sets that are open, and that use open ontologies and controlled vocabulary. Short term we will definitely take a hit if we have to drop all data, controlled vocabularies, and ontologies that aren't completely open and freely redistributable."

**Comment by diatomsRcool** [comment]
Does the "cross references to non-open terminologies are permissible" statement not make this ok?

**Comment by diatomsRcool** [comment]
@mellybelly ? thoughts?

**Comment by mellybelly** [comment]
Xrefs are fine and in fact need to be supported. 

@webyrd perhaps we can have some clause to the effect of:
If no open terminology or resource used within the Translator is available, a statement to this effect should be included:

"This resource, while not openly available to all, does not have alternative options and will be replaced at such time as one is created or is made available"

**Comment by diatomsRcool** [comment]
update added to the text.
