### ISSUE TITLE
Conflict resolution and issue reporting

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#4]
In the Code of Conduct: 
**Reporting issues.** If a community member experiences or witnesses unacceptable behavior, or if any other concern arises, then please report it by contacting a member of the SRI leadership team (Mungall, Haendel, or Bizon). If none of the aforementioned SRI leads are suitable, or if the issue involves an SRI lead, then please contact NCATS (Colvis or Southall). Finally, if these options are not sufficient, then our recommendation is to contact your local ombuds office as a starting point for resolving the issue of concern.

Michel Dumontier comments: "i'd first encourage discussion of transgressions with the responsible PI or PIs in the team. if the issue is between members of the same institution, it should follow institutional policy. if it involves members across institutions/teams, then it should escalate as a discussion between relevant PIs and members. if the conflict still is not satisfactorily resolved (according to a clear agreement as to what that constitutes), then it should escalate to NCATS and institutional governance."

Larry Hunter comments: "I think there should be a lighter weight way to raise a concern without a formal report to NCATS. A set of volunteers who make themselves available to discuss potential issues with community members, combined with some training for those people might be a good alternative."

**Comment by diatomsRcool** [comment]
@LEHunter Do you think we need some sort of a light weight grievance committee for this that would be one step before formally going to NCATS?

**Comment by LEHunter** [comment]
I do think that would be a good idea.  Optional, but a way to get community eyes on a problem at an early stage.

**Comment by diatomsRcool** [comment]
Language added to create a Grievance Committee and to add more detail to the reporting process
