### ISSUE TITLE
Steering Committee membership

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#7]
From Roles and Responsibilities:
"SC members will be nominated by each of the funded projects, and the entire Biomedical Data Translator Consortium will vote. SC terms will be 2 years and staggered such that there is always overlap. Initially, some terms will be one year to accommodate this cycle and will be determined by the SC members. If a SC member’s Translator funding expires before the end of their term, they must be replaced by a member that is currently funded by Translator to finish their term. The replacement will be chosen by majority vote of the SC. Note that each institution is limited to one representative on the SC at a time."

Andrew Su comments: "Not quite understanding the rationale here. If the SC will be comprised of one member from each team, most often the SC rep would be the PI? If a team wanted their rep to be the PI for the whole funding period, would that be disallowed?"

**Comment by mellybelly** [comment]
Our thoughts were to support a bit more dynamic exchange - so does not need to be the PI and does not need to stay the same person. On the other hand, if the team prefers to keep the same person the whole time, i suppose if everyone agrees that that is ok, that we should allow that?

**Comment by mellybelly** [comment]
@andrewsu

**Comment by andrewsu** [comment]
I also don't understand the voting. Is every team placing a member on the SC? Or is there size of the SC smaller than the number of funded projects?

**Comment by diatomsRcool** [comment]
Every funded project can have a member on the SC and thus a vote on the SC. Each funded project can choose their rep on the SC as they like. Does that make sense?

**Comment by andrewsu** [comment]
I think that makes lots of sense and I would favor that simple policy/text.

**Comment by diatomsRcool** [comment]
OK, so this changes the current wording that every funded project will nominate a representative and the entire Translator consortium votes on whether or not that rep will be on the SC. 
The proposal now is to change it so that each funded team chooses their own rep for the SC and they get to join the SC without a larger vote. Any objections to that change?

**Comment by cbizon** [comment]
I think each funded project needs a member on the SC, so I think it's a good change.

**Comment by diatomsRcool** [comment]
Change made.
