### ISSUE TITLE
Change process for governance docs

### ISSUE THREAD

**Issue by diatomsRcool** [TranslatorIIPrototypes/SRIGovernance#9]
Standards and Reference Change Management document:
"Changes to Translator governance can be proposed by any community member and are voted on by the Steering Committee during a regular meeting. "

Noel Southall comments: "At some point. Maybe for now we want to see how dynamic a document it needs to be? Maybe a provisional /non-binding content type/process that allows some volatile content that gets adopted after a certain period of use (or lack thereof)?"

Stephen Ramsay comments: "Why can't the SC vote asynchronously on a proposed change, if the members all are willing? This seems like it could slow the project down. (meetings are quarterly, per the R&R doc)."

**Comment by diatomsRcool** [comment]
We can include a provision for asynchronous voting via slack, if all are amenable.

**Comment by cbizon** [comment]
I'm ok with async, but I'd rather it was in github rather than slack (because of permanence/transience)

**Comment by diatomsRcool** [comment]
OK. I can write a paragraph about asynchronous voting in GitHub in the governance doc.

**Comment by diatomsRcool** [comment]
Change made.
